"""⌘F 面板第三塊：找重複單字並刪除（含分組、比較欄位等純函式）。"""

import os
import re
import time
from aqt import mw
from aqt.qt import (
    QDialog, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QScrollArea, QWidget, QCheckBox, QPixmap, QIcon, QSize, QMessageBox, Qt,
)
from ._text import _clean_text
from ._batch import _blocked_by_batch, _deck_note_ids, _section_title, _sync_after_batch


def _duplicate_groups(items):
    """[(nid, raw Front)] → [(key, [nid, …])] for keys shared by 2+ notes, sorted by key.
    key = Front after HTML strip + lowercase, so mobile-added HTML / case variants of
    the same word land in one group. Blank Fronts are ignored."""
    from collections import defaultdict
    groups = defaultdict(list)
    for nid, front in items:
        key = _clean_text(front or "", lower=True)
        if key:
            groups[key].append(nid)
    return sorted((k, v) for k, v in groups.items() if len(v) > 1)


def _fully_checked_group(groups, checked):
    """First group key whose every card is in `checked`, else None.
    Deleting a whole group would remove the word entirely — the guard behind
    "keep at least one per group"."""
    for key, nids in groups:
        if all(n in checked for n in nids):
            return key
    return None


# 重複卡的比較欄位（Sentence 是每列的主文字，一定顯示，不在這裡）
DUPLICATE_COMPARE_FIELDS = ["Translation", "Sentence_CN", "Association"]


DUPLICATE_THUMB_PX = 64          # 清單縮圖的方框邊長


DUPLICATE_PREVIEW_PX = 480       # 點縮圖放大時的最長邊


def _differing_fields(notes, fields=DUPLICATE_COMPARE_FIELDS):
    """Fields whose cleaned value is not the same on every note of a duplicate group,
    in `fields` order. Same-on-all fields are left out so the rows show only what
    tells the cards apart."""
    out = []
    for f in fields:
        values = {_clean_text((n[f] if f in n else "") or "") for n in notes}
        if len(values) > 1:
            out.append(f)
    return out


def _review_summary(reps, ivl):
    """reps = total reviews, ivl = interval in days → short text for a duplicate row."""
    if not reps:
        return "never reviewed"
    text = f"{reps} review" + ("" if reps == 1 else "s")
    if ivl and ivl > 0:
        text += f" · {ivl}-day interval"
    return text


def _image_filename(value):
    """First <img src="…"> filename in a field, or None (no image / leftover HTML)."""
    m = re.search(r'<img[^>]*\bsrc="([^"]+)"', value or "")
    return m.group(1) if m else None


def _review_stats(note):
    """(total reviews, longest interval) over the note's cards; (0, 0) if unreadable."""
    try:
        cards = [mw.col.get_card(cid) for cid in note.card_ids()]
        return sum(c.reps for c in cards), max((c.ivl for c in cards), default=0)
    except Exception:
        return 0, 0


class DuplicatesSection(QWidget):
    """Batch Operations section: list cards whose Front is the same after
    normalization (catches dupes that slipped in via mobile, which bypasses ⌘A's
    check) and delete the checked ones.
    Each row is a real QCheckBox, not a QTreeWidget item check indicator — the item
    indicator rendered invisible and ignored clicks inside the running Anki (2026-09-27,
    not reproducible outside it), while QCheckBox is what ⌘S uses and works there.
    Unlike the other sections, delete keeps a confirm dialog: cleared fields can be
    regenerated by ⌘S, a deleted card (and its review history) cannot."""

    def __init__(self, panel, parent=None):
        super().__init__(parent)
        self._panel = panel
        self._groups = []            # [(key, [nid, …])]
        self._boxes = []             # [(nid, QCheckBox)]
        self._setup_ui()
        self._scan()

    def _setup_ui(self):
        root = QVBoxLayout(self)
        root.setContentsMargins(0, 0, 0, 0)
        root.addWidget(_section_title("Find Duplicate Words"))

        desc = QLabel("Cards with the same word (ignoring case and HTML). Check the ones "
                      "to delete; keep at least one per word.")
        desc.setWordWrap(True)
        root.addWidget(desc)

        self.list_w = QWidget()
        self.list_layout = QVBoxLayout(self.list_w)
        self.list_layout.setContentsMargins(4, 4, 4, 4)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(self.list_w)
        scroll.setMinimumHeight(260)       # 一列含縮圖約 70px → 至少看得到一組兩張
        root.addWidget(scroll)

        self.status = QLabel("")
        self.status.setWordWrap(True)
        self.status.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.status.setStyleSheet("color:#16a34a; font-weight:600;")
        self.status.setVisible(False)
        root.addWidget(self.status)

        row = QHBoxLayout()
        row.addStretch()
        self.del_btn = QPushButton("Delete Checked")
        self.del_btn.setEnabled(False)
        self.del_btn.clicked.connect(self._on_delete)
        row.addWidget(self.del_btn)
        root.addLayout(row)

    def _clear_list(self):
        while self.list_layout.count():
            w = self.list_layout.takeAt(0).widget()
            if w is not None:
                w.deleteLater()
        self._boxes = []

    def _scan(self):
        self._clear_list()
        notes = {nid: mw.col.get_note(nid) for nid in _deck_note_ids()}
        self._groups = _duplicate_groups((nid, n["Front"]) for nid, n in notes.items())
        if not self._groups:
            self.list_layout.addWidget(QLabel("No duplicate cards."))
            self.del_btn.setEnabled(False)
            return
        media_dir = mw.col.media.dir()
        for key, nids in self._groups:
            head = QLabel(f"{key}  ({len(nids)} cards)")
            head.setStyleSheet("font-weight:600; color:#1E293B;")
            self.list_layout.addWidget(head)
            group_notes = [notes[nid] for nid in nids]
            diff = _differing_fields(group_notes)
            for nid in nids:
                self.list_layout.addWidget(self._card_row(nid, notes[nid], diff, media_dir))
        self.del_btn.setEnabled(True)

    def _card_row(self, nid, note, diff, media_dir):
        """One card: thumbnail (click to enlarge) | checkbox with the sentence, then
        added date + review history, then only the fields that differ in its group."""
        # 縮排交給外層 layout，勾選框本身不套 stylesheet（同 ⌘S 的 FieldRow）——
        # 套 margin 時，實際 Anki 裡方框畫的位置與可點的位置錯開，點方框沒反應
        row = QWidget()
        lay = QHBoxLayout(row)
        lay.setContentsMargins(16, 2, 0, 2)
        lay.addWidget(self._thumb(_image_filename(note["Image_Prompt"]), media_dir),
                      0, Qt.AlignmentFlag.AlignTop)

        text = QVBoxLayout()
        text.setSpacing(1)
        sentence = _clean_text(note["Sentence"])[:70] or "(no sentence)"
        box = QCheckBox(sentence)
        text.addWidget(box)
        added = time.strftime("%Y-%m-%d", time.localtime(nid // 1000))
        meta = QLabel(f"added {added} · {_review_summary(*_review_stats(note))}")
        meta.setStyleSheet("color:#64748b;")
        text.addWidget(meta)
        if diff:
            parts = [f"{f}: {_clean_text(note[f]) or '(empty)'}" for f in diff]
            diff_lbl = QLabel(" · ".join(parts))
            diff_lbl.setWordWrap(True)
            diff_lbl.setStyleSheet("color:#475569;")
            text.addWidget(diff_lbl)
        lay.addLayout(text, 1)
        self._boxes.append((nid, box))
        return row

    def _thumb(self, filename, media_dir):
        """Fixed-size square: image scaled to fit (never cropped, never stretched),
        or a 'no image' placeholder. A button, so one click opens the large view."""
        px = DUPLICATE_THUMB_PX
        path = os.path.join(media_dir, filename) if filename else None
        pix = QPixmap(path) if path and os.path.exists(path) else QPixmap()
        if pix.isNull():
            lbl = QLabel("no image")
            lbl.setFixedSize(px, px)
            lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
            lbl.setStyleSheet("color:#94a3b8; font-size:10px; border:1px dashed #cbd5e1;")
            return lbl
        btn = QPushButton()
        btn.setFlat(True)
        btn.setFixedSize(px + 4, px + 4)
        btn.setIconSize(QSize(px, px))
        btn.setIcon(QIcon(pix.scaled(px, px, Qt.AspectRatioMode.KeepAspectRatio,
                                     Qt.TransformationMode.SmoothTransformation)))
        btn.setToolTip("Click to enlarge")
        btn.clicked.connect(lambda _=False, p=path: self._show_image(p))
        return btn

    def _show_image(self, path):
        """Large view of one card image: longest side DUPLICATE_PREVIEW_PX. Esc or the
        window's close button returns to the list. Non-blocking, one at a time."""
        pix = QPixmap(path)
        if pix.isNull():
            return
        side = DUPLICATE_PREVIEW_PX
        if max(pix.width(), pix.height()) > side:
            pix = pix.scaled(side, side, Qt.AspectRatioMode.KeepAspectRatio,
                             Qt.TransformationMode.SmoothTransformation)
        old = getattr(self, "_preview", None)
        if old is not None:
            old.close()
        dlg = QDialog(self.window())
        dlg.setWindowTitle(os.path.basename(path))
        lay = QVBoxLayout(dlg)
        img = QLabel()
        img.setPixmap(pix)
        lay.addWidget(img)
        self._preview = dlg
        dlg.show()

    def _checked(self):
        return [nid for nid, box in self._boxes if box.isChecked()]

    def _say(self, text):
        self.status.setText(text)
        self.status.setVisible(True)

    def _on_delete(self):
        if _blocked_by_batch(self._say):     # 別在批次寫卡時把卡刪掉
            return
        to_delete = self._checked()
        if not to_delete:
            self._say("No cards checked.")
            return
        whole = _fully_checked_group(self._groups, set(to_delete))
        if whole is not None:
            self._say(f"Every '{whole}' card is checked; keep at least one.")
            return
        reply = QMessageBox.question(
            self, "Confirm Deletion",
            f"Delete the {len(to_delete)} checked card(s)? This cannot be undone.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
        )
        if reply != QMessageBox.StandardButton.Yes:
            return
        mw.col.remove_notes(to_delete)
        mw.col.save()
        mw.reset()
        _sync_after_batch()
        self._scan()
        self._say(f"✓ Deleted {len(to_delete)} card(s).")
